spring:
  application:
    name: 6._ApplicationClosingRESTAPI-3
  boot:
    admin:
      client:
        url:
        - http://localhost:1111/
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
