spring:
  application:
    name: GreetRestAPI
  boot:
    admin:
      client:
        url:
        - http://localhost:1111/
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
