spring:
  application:
    name: 4._GreetRESTAPI-1
  boot:
    admin:
      client:
        url:
        - http://localhost:1111/
server:
  port: 9099
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'