spring:
  application:
    name: WelcomeRESTAPI
  boot:
    admin:
      client:
        url:
        - http://localhost:1111/
server:
  port: 8081
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost8761/eureka
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
